name: Deploy Camunda Resources

on:
  push:
    branches: ["dev"]
    paths:
      - 'camunda/*'

jobs:
  deploy-resources:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy Updated Resources
        uses: camunda-community-hub/camunda-platform-8-github-action@master
        with:
          clientConfig: ${{ secrets.ZEEBE_CLIENT_CONFIG }}
          operation: deployResource
          resourceDirectory: camunda
